document.write('<footer aria-label="Nettstedets bunntekst" id="contact">');
document.write('        <div class="footer top-footer">');
document.write('            <h2>Kontakt meg</h2>');
document.write('            <div>');
document.write('                <p><a href="mailto:evafhaugum@hotmail.com">evafhaugum@hotmail.com</a></p>');
document.write('            </div>');
document.write('');
document.write('            <div class="social-media">');
document.write('                <a href="https://www.linkedin.com/in/eva-fossen-haugum/" target="_blank">');
document.write('                    <img src="../assets/images/linkedin.png" alt="LinkedIn">');
document.write('                </a>');
document.write('                <a href="https://github.com/evafha" target="_blank">');
document.write('                    <img src="../assets/images/github.png" alt="GitHub">');
document.write('                </a>');
document.write('            </div>');
document.write('        </div>');
document.write('');
document.write('        <div class="footer bottom-footer">');
document.write('');
document.write('            <!-- SCROLL TO TOP BUTTON -->');
document.write('            <div class="scroll">');
document.write('                <a href="#mainContent" aria-label="hopp tilbake til toppen">TILBAKE TIL TOPPEN</a>');
document.write('            </div>');
document.write('');
document.write('            <!-- COPYRIGHT -->');
document.write('            <p class="copyright" tabindex="0">Copyright &#169; 2025 Eva Fossen Haugum</p>');
document.write('        </div>');
document.write('');
document.write('    </footer>');
